### ISSUE TITLE
Building On Local gives error on Both Win7 and Ubuntu environment.

### ISSUE THREAD

**Issue by hrath2015** [reactioncommerce/redoc#12]
Please see the Error Log Below.

Error: Can't find npm module 'classnames'. Did you forget to call 'Npm.depends' in package.js within
    at Object.Npm.require (D:\Devprojects\docs\.meteor\local\build\programs\server\boot.js:175:17)
    at options.fallback (packages/modules/modules.js:20:1)
    at require (packages/modules/.npm/package/node_modules/install/install.js:79:1)
    at meteorInstall.app.common.docs.toc.jsx (common/docs/toc.jsx:3:56)
    at fileEvaluate (packages/modules/.npm/package/node_modules/install/install.js:183:1)
    at require (packages/modules/.npm/package/node_modules/install/install.js:75:1)
    at meteorInstall.app.common.docs.docs.jsx (common/docs/docs.jsx:2:40)
    at fileEvaluate (packages/modules/.npm/package/node_modules/install/install.js:183:1)
    at require (packages/modules/.npm/package/node_modules/install/install.js:75:1)
    at D:\Devprojects\docs\.meteor\local\build\programs\server\app\app.js:1507:1

**Comment by hrath2015** [comment]
Was able to run it.  Thanks
