### ISSUE TITLE
Your application is crashing

### ISSUE THREAD

**Issue by ssmlee04** [reactioncommerce/redoc#65]
I was trying to do `meteor --settings settings.json ` and I got the following error messages:

```
I20170118-10:22:06.416(8) (percolate_synced-cron.js:87) SyncedCron: Scheduled "Update Repo Cache" next run @Wed Jan 18 2017 12:00:00 GMT+0800 (CST)
I20170118-10:22:06.419(8) (percolate_synced-cron.js:87) SyncedCron: Scheduled "Flush Docs Cache" next run @Wed Jan 18 2017 12:00:00 GMT+0800 (CST)
W20170118-10:22:06.915(8)? (STDERR) /Users/username/.meteor/packages/meteor-tool/.1.4.2_3.1rd9djy++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:313
W20170118-10:22:06.916(8)? (STDERR)             throw(ex);
W20170118-10:22:06.916(8)? (STDERR)             ^
W20170118-10:22:06.917(8)? (STDERR) 
W20170118-10:22:06.917(8)? (STDERR) Error: failed [404] 404: Not Found 
W20170118-10:22:06.917(8)? (STDERR)     at Object.Future.wait (/Users/username/.meteor/packages/meteor-tool/.1.4.2_3.1rd9djy++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:449:15)
W20170118-10:22:06.918(8)? (STDERR)     at Object.call (packages/meteor.js:213:24)
W20170118-10:22:06.918(8)? (STDERR)     at Object.HTTP.get (packages/http/httpcall_common.js:50:20)
W20170118-10:22:06.918(8)? (STDERR)     at getRepoData (packages/reactioncommerce:redoc-core/server/methods/repoData.js:82:35)
W20170118-10:22:06.919(8)? (STDERR)     at updateRepoData (packages/reactioncommerce:redoc-core/server/methods/repoData.js:108:22)
W20170118-10:22:06.919(8)? (STDERR)     at packages/reactioncommerce:redoc-core/server/startup.js:54:3
W20170118-10:22:06.919(8)? (STDERR)     at Function.time (/Users/username/Desktop/redoc/.meteor/local/build/programs/server/profile.js:301:28)
W20170118-10:22:06.919(8)? (STDERR)     at /Users/username/Desktop/redoc/.meteor/local/build/programs/server/boot.js:304:13
W20170118-10:22:06.920(8)? (STDERR)     at /Users/username/Desktop/redoc/.meteor/local/build/programs/server/boot.js:345:5
W20170118-10:22:06.920(8)? (STDERR)     at Function.run (/Users/username/Desktop/redoc/.meteor/local/build/programs/server/profile.js:480:12)
W20170118-10:22:06.920(8)? (STDERR)     - - - - -
W20170118-10:22:06.920(8)? (STDERR)     at makeErrorByStatus (packages/http/httpcall_common.js:13:10)
W20170118-10:22:06.921(8)? (STDERR)     at Request._callback (packages/http/httpcall_server.js:113:17)
W20170118-10:22:06.921(8)? (STDERR)     at Request.self.callback (/Users/username/.meteor/packages/http/.1.2.10.3yb3pj++os+web.browser+web.cordova/npm/node_modules/request/request.js:200:22)
W20170118-10:22:06.921(8)? (STDERR)     at emitTwo (events.js:87:13)
W20170118-10:22:06.922(8)? (STDERR)     at Request.emit (events.js:172:7)
W20170118-10:22:06.922(8)? (STDERR)     at Request.<anonymous> (/Users/username/.meteor/packages/http/.1.2.10.3yb3pj++os+web.browser+web.cordova/npm/node_modules/request/request.js:1067:10)
W20170118-10:22:06.923(8)? (STDERR)     at emitOne (events.js:82:20)
W20170118-10:22:06.923(8)? (STDERR)     at Request.emit (events.js:169:7)
W20170118-10:22:06.923(8)? (STDERR)     at IncomingMessage.<anonymous> (/Users/username/.meteor/packages/http/.1.2.10.3yb3pj++os+web.browser+web.cordova/npm/node_modules/request/request.js:988:12)
W20170118-10:22:06.924(8)? (STDERR)     at emitNone (events.js:72:20)
=> Exited with code: 1
=> Your application is crashing. Waiting for file change.
```

I was wondering if there's anything that I did wrong? Thanks.

**Comment by aaronjudd** [comment]
@ssmlee04 Did you ever resolve this? Not 100% sure, but looks like bad settings data, maybe there's the initRepoData object is invalid. 
It should be :
```
"redoc": {
  "initRepoData": "https://raw.githubusercontent.com/reactioncommerce/redoc/master/private/redoc.json"
}
```
Re-open if that's not it.
